# Packs files into one C++ header, deflated -- see src/inflate.h.
#
# Run as a build step:
#
#   cmake -DOUTPUT=<header> -DDIR=<dir> -DFILES=<file=kName,...> -P embed_packed.cmake
#
# Each <file> is read from <dir> and becomes a cap::Packed called kName. The
# pairs are separated by commas rather than a CMake list: a semicolon inside a
# build command is one more thing for the shell in between to take apart.
#
# CMake compresses through the zlib it carries, at the highest level, and writes
# gzip around it. Only the deflate data inside goes into the header: the gzip
# header holds the time of packing, and would make every build a new header.
# That leaves the header rewritten only when its content changes, so packing the
# same files again does not rebuild what includes it.

if(NOT OUTPUT OR NOT DIR OR NOT FILES)
  message(FATAL_ERROR "embed_packed.cmake: OUTPUT, DIR and FILES are required")
endif()
string(REPLACE "," ";" files "${FILES}")

set(text "// Generated by tools/embed_packed.cmake. Do not edit.\n")
string(APPEND text "#pragma once\n#include <cstdint>\n#include \"inflate.h\"\nnamespace cap {\n")

set(gz "${OUTPUT}.gz")
foreach(entry IN LISTS files)
  if(NOT entry MATCHES "^([A-Za-z0-9_.]+)=([A-Za-z_][A-Za-z0-9_]*)$")
    message(FATAL_ERROR "embed_packed.cmake: expected file=name, got '${entry}'")
  endif()
  set(file "${DIR}/${CMAKE_MATCH_1}")
  set(name "${CMAKE_MATCH_2}")

  file(SIZE "${file}" size)
  if(size EQUAL 0)
    message(FATAL_ERROR "embed_packed.cmake: ${file} is empty")
  endif()
  # SPIR-V is a stream of 32-bit words, which the renderer unpacks into words
  # and hands over as they are -- little-endian, as dxc writes them.
  if(file MATCHES "\\.spv$")
    file(READ "${file}" magic HEX LIMIT 4)
    math(EXPR rest "${size} % 4")
    if(NOT magic STREQUAL "03022307" OR NOT rest EQUAL 0)
      message(FATAL_ERROR "embed_packed.cmake: ${file} is not little-endian SPIR-V")
    endif()
  endif()

  file(ARCHIVE_CREATE OUTPUT "${gz}" PATHS "${file}" FORMAT raw
       COMPRESSION GZip COMPRESSION_LEVEL 9)
  file(READ "${gz}" hex HEX)
  file(REMOVE "${gz}")
  # 10 bytes of gzip header -- deflate, no flags, so nothing optional follows --
  # then the deflate data, then CRC-32 and the unpacked size in 8 bytes.
  if(NOT hex MATCHES "^1f8b0800")
    message(FATAL_ERROR "embed_packed.cmake: unexpected gzip header for ${file}")
  endif()
  string(LENGTH "${hex}" length)
  math(EXPR deflate_length "${length} - 36")
  math(EXPR trailer "${length} - 8")
  string(SUBSTRING "${hex}" 20 ${deflate_length} deflate)
  string(SUBSTRING "${hex}" ${trailer} 8 isize)
  string(REGEX REPLACE "(..)(..)(..)(..)" "\\4\\3\\2\\1" isize "${isize}")
  math(EXPR isize "0x${isize}")
  if(NOT isize EQUAL size)
    message(FATAL_ERROR "embed_packed.cmake: ${file} packed to ${isize} bytes, not ${size}")
  endif()

  string(REGEX REPLACE "(..)" "0x\\1," bytes "${deflate}")
  # Sixteen bytes to a line. CMake's regular expressions have no {n}.
  string(REPEAT "0x..," 16 line)
  string(REGEX REPLACE "(${line})" "\\1\n  " bytes "${bytes}")
  string(REGEX REPLACE "\n  $" "" bytes "${bytes}")

  string(APPEND text "static const uint8_t ${name}Data[] = {\n  ${bytes}\n};\n")
  string(APPEND text "static const Packed ${name} = {${name}Data, sizeof(${name}Data), ${size}};\n")
endforeach()

string(APPEND text "}  // namespace cap\n")

file(WRITE "${OUTPUT}.tmp" "${text}")
configure_file("${OUTPUT}.tmp" "${OUTPUT}" COPYONLY)
file(REMOVE "${OUTPUT}.tmp")
