# Turns compiled SPIR-V files into one C++ header of uint32_t arrays.
#
# Run as a build step:
#
#   cmake -DOUTPUT=<header> -DSPIRV_DIR=<dir> -DSHADERS=<file=kName,...> -P embed_spirv.cmake
#
# Each <file> is <dir>/<file>.spv, and kName the array it becomes. The pairs are
# separated by commas rather than a CMake list: a semicolon inside a build
# command is one more thing for the shell in between to take apart.
#
# SPIR-V is a stream of 32-bit words, and vkCreateShaderModule wants them
# aligned as such -- an array of bytes would only be aligned by luck. dxc writes
# the words little-endian, which is what every machine qBlank runs on reads, so
# each group of four bytes is turned around into one hexadecimal word.
#
# The header is only rewritten when its content changes, so recompiling a
# shader into the same bytes does not rebuild the renderer.

if(NOT OUTPUT OR NOT SPIRV_DIR OR NOT SHADERS)
  message(FATAL_ERROR "embed_spirv.cmake: OUTPUT, SPIRV_DIR and SHADERS are required")
endif()
string(REPLACE "," ";" shaders "${SHADERS}")

set(text "// Generated by tools/embed_spirv.cmake from src/render/shaders.h. Do not edit.\n")
string(APPEND text "#pragma once\n#include <cstdint>\nnamespace cap {\n")

foreach(entry IN LISTS shaders)
  if(NOT entry MATCHES "^([A-Za-z0-9_]+)=([A-Za-z_][A-Za-z0-9_]*)$")
    message(FATAL_ERROR "embed_spirv.cmake: expected file=name, got '${entry}'")
  endif()
  set(file "${SPIRV_DIR}/${CMAKE_MATCH_1}.spv")
  set(name "${CMAKE_MATCH_2}")

  file(SIZE "${file}" size)
  math(EXPR rest "${size} % 4")
  if(size EQUAL 0 OR NOT rest EQUAL 0)
    message(FATAL_ERROR "embed_spirv.cmake: ${file} is ${size} bytes, not whole words")
  endif()

  file(READ "${file}" hex HEX)
  if(NOT hex MATCHES "^03022307")
    message(FATAL_ERROR "embed_spirv.cmake: ${file} is not little-endian SPIR-V")
  endif()
  string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," words "${hex}")
  # Eight words to a line. CMake's regular expressions have no {n}.
  string(REPEAT "0x[0-9a-f]+," 8 line)
  string(REGEX REPLACE "(${line})" "\\1\n  " words "${words}")
  string(REGEX REPLACE "\n  $" "" words "${words}")

  string(APPEND text "static const uint32_t ${name}[] = {\n  ${words}\n};\n")
endforeach()

string(APPEND text "}  // namespace cap\n")

file(WRITE "${OUTPUT}.tmp" "${text}")
configure_file("${OUTPUT}.tmp" "${OUTPUT}" COPYONLY)
file(REMOVE "${OUTPUT}.tmp")
